name: Build

on:
  workflow_dispatch:
  pull_request_target: # Safely handles forks by running trusted base code
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop/test-ci
    tags:
      - '*'
jobs:
  Linux532:
    environment: dev
    uses: ./.github/workflows/buildLinux.yml
    secrets: inherit
    with:
      runner-label: ubuntu-22.04
      unreal-engine-version: "5.3.2"
      unreal-engine-zip: "s3://rmf2-unreal-engine/5.3.2/Linux_Unreal_Engine_5.3.2.zip"
      unreal-program-name: "UE_5.3.2"
      upload-package-base-name: "RMF2ForUnreal-532-linux"
      clang-version: "v22_clang-16.0.6-centos7"
